AlelaProject/Controllers/NuevoPuestoController.cs
using AlelaProject.Models;
using AlelaProject.Servicio;
using Dapper;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace AlelaProject.Controllers
{
    public class NuevoPuestoController : Controller
    {
        public string id { get; set; }
        public int idc { get; set; }
        string conexionData = Helper.Coneccion;
        // GET: NuevoPuesto
        public ActionResult Index()
        {
            ViewBag.NombreCompleto = System.Web.HttpContext.Current.Session["NombreCompleto"] as String;
            ViewBag.IdUser = System.Web.HttpContext.Current.Session["IdUser"] as String;
            ViewBag.idPerfil = System.Web.HttpContext.Current.Session["idPerfil"] as String; ;
            ViewBag.NombrePerfil = System.Web.HttpContext.Current.Session["NombrePerfil"] as String;
            ViewBag.urlima = System.Web.HttpContext.Current.Session["urlima"] as String;


            if (string.IsNullOrEmpty(ViewBag.NombreCompleto))
            {
                return RedirectToAction("Index", "Home");
            }
            ConsultaArea();
            ConsultaTipoObjeto();
            ConsultaComplementos();
            return View();
        }

        public void ConsultaArea()
        {

            var Consulta = "select idArea,NombreArea from tblArea";

            using (var conexion = new SqlConnection(conexionData))
            {
                var Data = conexion.Query<Area>(Consulta).ToList();

                if (Data.Count == 0)
                {
                    ViewBag.Data = null;
                }
                else
                {
                    List<SelectListItem> item = Data.ConvertAll(d =>
                    {
                        return new SelectListItem()
                        {
                            Text = d.NombreArea.ToString(),
                            Value = d.idarea.ToString(),
                            Selected = false
                        };
                    });

                    ViewBag.Data = item;
                }
            }
        }

        public void ConsultaTipoObjeto()
        {

            var Consulta = "select idTipoObjeto,TipoObjeto as Tipo from tblTipoObjeto";

            using (var conexion = new SqlConnection(conexionData))
            {
                var Data2 = conexion.Query<TipoObjeto>(Consulta).ToList();

                if (Data2.Count == 0)
                {
                    ViewBag.Data2 = null;
                }
                else
                {
                    List<SelectListItem> item = Data2.ConvertAll(d =>
                    {
                        return new SelectListItem()
                        {
                            Text = d.Tipo.ToString(),
                            Value = d.idTipoObjeto.ToString(),
                            Selected = false
                        };
                    });

                    ViewBag.Data2 = item;
                }
            }
        }

        public void ConsultaComplementos()
        {
            string conexionData = Helper.Coneccion;
            var Consulta = "select idComplemento,NombreComplemento from tblComplemento";

            using (var conexion = new SqlConnection(conexionData))
            {
                var Data3 = conexion.Query<Complemento>(Consulta).ToList();

                if (Data3.Count == 0)
                {
                    ViewBag.Error = "No hay Sedes disponibles";
                }
                else
                {
                    ViewBag.Datos3 = Data3;
                }
            }
        }

        public ActionResult IndexAceptarmuliple(string[] ids, string Area, string Nombre, string Codigo, string TipoObjeto)
        {
            //Insertamos el Elemento.
            var Consulta = "insert into tblObjetos(Nombre,Codigo,idArea,idTipoObjeto)values(@Nombre,@Codigo,@idArea,@idTipoObjeto)";

            using (var conexion = new SqlConnection(conexionData))
            {
                conexion.Execute(Consulta, new { Nombre = Nombre.ToUpper(), Codigo = Codigo, idArea = Area, idTipoObjeto = TipoObjeto });
            }

            //Consultamos el idgenerado

            var Consulta2 = "select idObjeto from tblObjetos where Nombre = '" + Nombre + "' and Codigo = '" + Codigo + "' and idArea = '" + Area + "'";
            string idObjeto;
            using (var conexion = new SqlConnection(conexionData))
            {
                var Data = conexion.Query<Elemento>(Consulta2).ToList();

                if (Data.Count == 0)
                {
                    ViewBag.Error = "No hay Areas disponibles";
                }
                else
                {
                    ViewBag.Datos = Data;
                }
            }

            idObjeto = ViewBag.Datos[0].idObjeto;

            id = ids[0];

            string[] array = id.Split(',');

            idc = array[0].Count();

            if (idc > 0)
            {
                foreach (var item in array)
                {
                    try
                    {
                        Thread.Sleep(500);
                        //Insertamos el cada Complemento de cada objeto o puesto de trabajo.
                        var Consulta3 = "insert into tblObjetoComplemento(idObjeto,idComplemento)values(@idObjeto,@idComplemento)";

                        using (var conexion = new SqlConnection(conexionData))
                        {
                            conexion.Execute(Consulta3, new { idObjeto = idObjeto, idComplemento = item });
                        }
                    }
                    catch
                    {

                    }
                }

            }
            return RedirectToAction("Index", "Elementos");
        }

        public ActionResult GoToBack()
        {
            return RedirectToAction("Index", "Elementos");
        }
    }
}

AlelaProject/Views/NuevoPuesto/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
    List<SelectListItem> Area = (List<SelectListItem>)ViewBag.Data;
    List<SelectListItem> TipoObjeto = (List<SelectListItem>)ViewBag.Data2;
}
<br />
<br />
<div class="alert-danger">
    @ViewBag.Error
</div>
<br />
<br />
<div class="container border">
    <h3 class="text-info center" style="padding-top:2em;padding-left:1em">Nuevo Elemento de Trabajo</h3>
    <hr />
    <div class="form-group">
        <form class="form-group" asp-action="Index" id="formulario">
            <br />
            <div class="row col-md-12">
                <div class="form-group col-md-3">
                    <label>Seleccione Area<span style="color:red"><b> *</b></span></label>
                    @Html.DropDownList("Area", Area, "Selecciona Area", new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                    <div class="form-group col-md-12">
                        <label>Nombre Objeto<span style="color:red"><b> *</b></span></label>
                        <input id="Nombre" name="Nombre" class="form-control" type="text" style="width:260px" />
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group col-md-12">
                        <label>Código<span style="color:red"><b> *</b></span></label>
                        <input id="Codigo" name="Codigo" class="form-control" type="text" style="width:260px" />
                    </div>
                </div>
                <div class="form-group col-md-3">
                    <label>Seleccione Tipo Objeto<span style="color:red"><b> *</b></span></label>
                    @Html.DropDownList("TipoObjeto", TipoObjeto, "Selecciona Tipo Objeto", new { @class = "form-control" })
                </div>
            </div>
            <br />
            <br />
            <span class="text-info left row" style="padding-left:1em;font-size:18px; font-weight:bold">Complemento</span>
            <br />
            <br />
            <div class="col-md-12">
                <br />
                @if (ViewBag.Datos3 != null)
                {
                    foreach (var item in ViewBag.Datos3)
                    {
                        <table><tr id="itemNov"><td><input type="checkbox" id="@item.idComplemento" checked="@item.Seleccioando" /><span style="font-size:15px;font-weight:bold; color:black">    @item.NombreComplemento</span></td></tr></table>}
                }
            </div>
        </form>
    </div>
</div>
<br />
<div class="row col-md-4">
    <div class="form-group col-md-6 text-left" style="width:300px">
        <button class="btn btn-info" onclick="lista();" style="width:150px">Aceptar</button>
    </div>
    <div class="form-group col-md-6 text-right" style="width:300px;">
        <button class="btn btn-dark" type="button" style="width:150px" onclick="location.href='@Url.Action("GoToBack", "NuevoPuesto")'">Cancelar</button>
    </div>
</div>
<script>
    var lista = function () {
        var Nombre = $("#Nombre").val();
        var Codigo = $("#Codigo").val();
        var Area = document.getElementById('Area').selectedOptions[0].value;
        var TipoObjeto = document.getElementById('TipoObjeto').selectedOptions[0].value;

        var arregloitems = [];

        var coma = "";

        $("#itemNov td input[type=checkbox]").each(function (index, val) {

            var current = $(val).attr("Id");

            var isChecked = $("#" + current).is(":checked", true);

            if (isChecked) {
                arregloitems.push(current);
            }

        })
        location.href = '@Url.Action("IndexAceptarmuliple", "NuevoPuesto")?ids=' + arregloitems + '&Area=' + Area + '&Nombre=' + Nombre + '&Codigo=' + Codigo + '&TipoObjeto=' + TipoObjeto;
    }
</script>