AlelaProject/Controllers/TableroControlController.cs
using AlelaProject.Models;
using AlelaProject.Servicio;
using Dapper;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlelaProject.Controllers
{
    public class TableroControlController : Controller
    {
        public static string idUsuario { get; set; }
        public static string CorreoElectronico { get; set; }
        public static string idPerfil { get; set; }
        public static List<Datos> _datosgrafico = new List<Datos>();

        string conexionData = Helper.Coneccion;
        // GET: TableroControl
        public ActionResult Index()
        {
            ViewBag.NombreCompleto = System.Web.HttpContext.Current.Session["NombreCompleto"] as String;
            ViewBag.IdUser = System.Web.HttpContext.Current.Session["IdUser"] as String;
            CorreoElectronico = System.Web.HttpContext.Current.Session["Correo"] as String;
            ViewBag.idPerfil = System.Web.HttpContext.Current.Session["idPerfil"] as String;
            ViewBag.NombrePerfil = System.Web.HttpContext.Current.Session["NombrePerfil"] as String;
            ViewBag.urlima = System.Web.HttpContext.Current.Session["urlima"] as String;


            if (string.IsNullOrEmpty(ViewBag.NombreCompleto))
            {
                return RedirectToAction("Index", "Home");
            }
            var Fechahoy = DateTime.Now.ToString("yyyy-MM-dd");

            string nombredia = DateTime.Now.ToString("dddd");

            ViewBag.FechaConsulta = Fechahoy;

            DateTime Fechainicial, FechaFinal, fh;

            fh = System.DateTime.Now;
            switch (nombredia)
            {
                case "lunes":
                    Fechainicial = fh;
                    FechaFinal = fh.AddDays(5);
                    IndiceRiesgo(Fechainicial, FechaFinal);
                    break;
                case "martes":
                    Fechainicial = fh.AddDays(-1);
                    FechaFinal = fh.AddDays(4);
                    IndiceRiesgo(Fechainicial, FechaFinal);
                    break;
                case "miércoles":
                    Fechainicial = fh.AddDays(-2);
                    FechaFinal = fh.AddDays(2);
                    IndiceRiesgo(Fechainicial, FechaFinal);
                    break;
                case "jueves":
                    Fechainicial = fh.AddDays(-3);
                    FechaFinal = fh.AddDays(1);
                    IndiceRiesgo(Fechainicial, FechaFinal);
                    break;
                default:
                    Fechainicial = fh.AddDays(-4);
                    FechaFinal = fh;
                    IndiceRiesgo(Fechainicial, FechaFinal);
                    break;
            }
            var Consulta = "Select COUNT(tp.idUsuario) as Estadistica from DT_ControlUsuarios.dbo.tblusuarios tu inner join DT_ControlUsuarios.dbo.tblPermisos tp on tu.idUsuario = tp.idUsuario where idPortal = 4 and idEstado = 1 union all select count(*) from tblObjetos where idObjeto != 1224 union all select count(*) from tblReservas where Fecha = '" + Fechahoy + "' and idObjeto != 1224";
            int totalp = 0; int reservas = 0; int disponibilidad;
            using (var conexion = new SqlConnection(conexionData))
            {
                var Data = conexion.Query<Datos>(Consulta).ToList();

                for (int i = 0; i < Data.Count; i++)
                {
                    if (i == 0)
                    {
                        ViewBag.Usuarios = Convert.ToInt32(Data[0].Estadistica);
                    }
                    if (i == 1)
                    {
                        ViewBag.Objetos = Convert.ToInt32(Data[1].Estadistica);
                        totalp = Convert.ToInt32(Data[1].Estadistica);
                    }
                    if (i == 2)
                    {
                        ViewBag.Reservas = Convert.ToInt32(Data[2].Estadistica);
                        reservas = Convert.ToInt32(Data[2].Estadistica);
                    }
                }
            }

            disponibilidad = totalp - reservas;
            ViewBag.Disponibles = disponibilidad;

            //Consultamos la ocupacion para el dia actual
            List<MiReservas> reservashoy = new List<MiReservas>();

            Consulta = "select NombreCompleto,NOMBRE,HoraInicio,HoraFin from tblReservas tr " +
                "inner join tblObjetos tob on tr.idObjeto = tob.idObjeto " +
                "inner join DT_ControlUsuarios.dbo.tblUsuarios tu on tr.idUsuario = tu.idUsuario " +
                "where Fecha = '" + fh.ToString("yyyy-MM-dd") + "' and tr.idObjeto != 1224";

            using (var conexion = new SqlConnection(conexionData))
            {
                var _reservashoy = conexion.Query<MiReservas>(Consulta).ToList();
                if (_reservashoy.Count == 0)
                {
                    ViewBag.reservashoy = reservashoy;
                }
                else
                {
                    ViewBag.reservashoy = _reservashoy;
                }
            }

            return View();
        }

        public List<Datos> IndiceRiesgo(DateTime f1, DateTime f2)
        {
            string Consulta;
            _datosgrafico.Clear();

            Consulta = "Select Fecha from tblReservas where idObjeto != 1224 and Fecha between '" + f1.ToString("yyyy-MM-dd") + "' AND '" + f2.ToString("yyyy-MM-dd") + "' ORDER BY Fecha ASC";

            using (var conexion = new SqlConnection(conexionData))
            {
                var Data = conexion.Query<MiReservas>(Consulta).ToList();

                while (f1 <= f2)
                {
                    int contador = 0;
                    for (int o = 0; o < Data.Count; o++)
                    {
                        if (f1.ToString("yyyy-MM-dd") == Data[o].Fecha.ToString("yyyy-MM-dd"))
                        {
                            contador += 1;
                        }
                    }
                    string nombredia = f1.ToString("dddd");


                    _datosgrafico.Add(new Datos
                    {
                        NombreDia = nombredia,
                        Numero = contador,
                        Estadistica = 0
                    });
                    f1 += new TimeSpan(1, 0, 0, 0);
                }


            }

            return _datosgrafico;

        }
        public List<Datos> IndiceRiesgoGrafico()
        {
            return _datosgrafico;
        }
        public ActionResult VisualizacionIndice()
        {
            return Json(IndiceRiesgoGrafico(), JsonRequestBehavior.AllowGet);
        }

        public List<Datos> MasReservas()
        {
            string Consulta;
            List<Datos> datos = new List<Datos>();
            string Fecha = System.DateTime.Now.ToString("yyyy-MM-dd");
            Consulta = "select top 5 COUNT(idReserva) as reservas,NombreCompleto " +
                "from tblReservas tr inner join DT_ControlUsuarios.dbo.tblUsuarios tu on tr.idUsuario = tu.idUsuario " +
                "where Fecha <= '" + Fecha + "' and idObjeto != 1224 and tr.idObjeto != 1221 group by NombreCompleto order by reservas desc";

            using (var conexion = new SqlConnection(conexionData))
            {
                var Data = conexion.Query<Datos>(Consulta).ToList();
                datos = Data;
            }

            
            return datos;
        }
        public ActionResult VisualizacionMasReservas()
        {
            return Json(MasReservas(), JsonRequestBehavior.AllowGet);
        }
    }
}

AlelaProject/Views/TableroControl/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<div class="container-xxl">
    <br />
    <div class="row">
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
                <div class="inner">
                    <h3>Usuarios</h3>
                    <h5>@ViewBag.Usuarios</h5>
                </div>
                <div class="icon">
                    <i class="ion ion-bag"></i>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
                <div class="inner">
                    <h3>Puestos</h3>
                    <h5>@ViewBag.Objetos</h5>
                </div>
                <div class="icon">
                    <i class="ion ion-bag"></i>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-dark">
                <div class="inner">
                    <h3>Ocupación</h3>
                    <h5>@ViewBag.Reservas</h5>
                </div>
                <div class="icon">
                    <i class="ion ion-bag"></i>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-orange">
                <div class="inner">
                    <h3>Disponibilidad</h3>
                    <h5>@ViewBag.Disponibles</h5>
                </div>
                <div class="icon">
                    <i class="ion ion-bag"></i>
                </div>
            </div>
        </div>
        <br />
        <div class="card shadow col-md-12" style="height:100%">
            <div class="card-header py-3 col-md-12">
                <div class="col-md-9 left">
                    <div class="col-xs-12">
                        <h6 class="font-weight-bold text-primary">Reservas de espacios para el dia Actual <span class="badge bg-blue">@ViewBag.FechaConsulta</span> </h6>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @if (ViewBag.reservashoy != null)
                    {
                        <br />
                        <br />
                        <table id="tblProyecto" class="table" width="100%" style="font-family:'Trebuchet MS'">
                            <thead>
                                <tr>
                                    <td class="text-info" style="text-transform:capitalize;font-weight:bold;font-size:16px">
                                        Nombre Completo
                                    </td>
                                    <td class="text-info" style="text-transform:capitalize;font-weight:bold;font-size:16px">
                                        Puesto
                                    </td>
                                    <td class="text-info" style="text-transform:capitalize;font-weight:bold;font-size:16px">
                                        Hora Entrada
                                    </td>
                                    <td class="text-info" style="text-transform:capitalize;font-weight:bold;font-size:16px">
                                        Hora Salida
                                    </td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in ViewBag.reservashoy)
                                {
                                    <tr>
                                        <td>
                                            @item.NombreCompleto
                                        </td>
                                        <td>
                                            @item.Nombre
                                        </td>
                                        <td>
                                            @item.HoraInicio
                                        </td>
                                        <td>
                                            @item.HoraFin
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                </div>
            </div>
        </div>
        <br />
        <br />
        <div class="col-md-12">
            <div id="chart_div" style="width:500px; height:100%;"></div>
        </div>
        <br />
        <div class="col-md-12">
            <div id="chart_div2" style="width:500px; height:100%;"></div>
        </div>
    </div>
</div>

<script type="text/javascript" src="https://www.google.com/jsapi"></script> @*src="https://www.google.com/jsapi"*@
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script> @*src=https://www.gstatic.com/charts/loader.js*@
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> @*src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"*@
@*Graficos indice Mensual*@
<script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizacionIndice", "TableroControl")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChartALP(result);
                    });
                },
                Error: function () {
                    alert('Error cargando los datos');
                }
            });
        });

    function drawChartALP(result) {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Nombre Dia');
        data.addColumn('number', 'Reservas');


        var dataArray = [];

        $.each(result, function (i, obj) {
            dataArray.push([obj.NombreDia, obj.Numero]);
        });

        data.addRows(dataArray);

        var options = {
            title: "Reservas de espacios para la semana en curso",
            width: 1080,
            height: 500,
            bar: { groupWidth: '20%' }

        };

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));

        chart.draw(data, options);
    }
</script>
<script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizacionMasReservas", "TableroControl")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChartreservaspersonas(result);
                    });
                },
                Error: function () {
                    alert('Error cargando los datos');
                }
            });
        });

    function drawChartreservaspersonas(result) {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Nombre Completo');
        data.addColumn('number', 'reservas');


        var dataArray = [];

        $.each(result, function (i, obj) {
            dataArray.push([obj.NombreCompleto, obj.reservas]);
        });

        data.addRows(dataArray);

        var options = {
            title: "Top de usuarios que más reservan.",
            width: 1080,
            height: 500,
            bar: { groupWidth: '20%' }

        };

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div2'));

        chart.draw(data, options);
    }
</script>
<style>
    .small-box {
        border-radius: 0.25rem;
        box-shadow: 0 0 1px #ffffff;
        display: block;
        margin-bottom: 20px;
        position: relative;
    }

        .small-box > .inner {
            padding: 10px;
        }

        .small-box h3 {
            font-size: 2rem;
            font-weight: 700;
            margin: 0 0 10px;
            padding: 0;
            white-space: nowrap;
            color: #ffffff;
        }

        .small-box h5 {
            font-size: 2rem;
            font-weight: 100;
            margin: 0 0 10px;
            padding: 0;
            white-space: nowrap;
            color: #ffffff;
        }
</style>
@section Scripts
{
    <script src="~/lib/datatables.net/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables.net-bs4/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#tblProyecto").DataTable({
                language:
                {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    },
                    "buttons": {
                        "copy": "Copiar",
                        "colvis": "Visibilidad"
                    }
                }
            });
        });
    </script>
}